default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV["JOURNEY_BUDDY_DATABASE_PASSWORD"] %>
